input = 'qywzphxoiseldjrbaoagvkmanu,qywzphxeisulpjrbtfcgvkmanu,qywzxhooiseldjrbtfcgvcmanu,qywzphjojseldjubtfcgvkmanu,qtwzphxoieeldjrbtfcgvrmanu,tywzphzoiseldjritfcgvkmanu,qyuzphxoiseldjrbtfcgykbanu,qswzmhxoiseldjrbtfcgvkaanu,qyczqhxoiseldjrbtfcgvkbanu,qybzpqxooseldjrbtfcgvkmanu,qywzpoxoxseldjrbtfcgvpmanu,qywzphxbipeldjrbtfcgvkmaru,qywzpmxoiseldjrutqcgvkmanu,qywzphxoisesdjrrtfchvkmanu,qywzphxoiseldhrbtfcgukyanu,jywzphyoiseldjrbtfclvkmanu,qywzvhxoiselrjrbtfcgvkmanl,qywzplxojseldjrbtfcgvkmamu,qywzphxoiseldjrbtacgvkmvnd,qywpphxoiseldjrbtfcgvkvenu,qqazphxoiselqjrbtfcgvkmanu,qyozvhxoiseldjrbtfcgvkmadu,xywzphxliseldjhbtfcgvkmanu,qdwzphioiseldqrbtfcgvkmanu,qswyphxoiseldjrbtfcgvkmanx,qowzshxoiseldjrbtfigvkmanu,qywzphxoiseldjjbtfcgvkmawq,qyhzphxoiseldjrbtfvgvkmynu,qxwzphxoiselmjrbtfcgvqmanu,qywzphxoiceldjrbtfcgikmgnu,qywephxoiseldjrbthcgvkmane,yywzphxoisejdjrotfcgvkmanu,qywzxhxoisyldyrbtfcgvkmanu,qywzpjxoiseqdjrbtfcgvwmanu,qywzphxoqweldprbtfcgvkmanu,qywzphnoiseldjrbtfcamkmanu,qylgphxoiseldjrbtfcgvkmauu,qysdphxomseldjrbtfcgvkmanu,lywzpoxoikeldjrbtfcgvkmanu,qywzphxgiseldjrbtfeqvkmanu,qywzdhxozseldjcbtfcgvkmanu,qywzphxeiskedjrbtfcgvkmanu,qmwzphxoispldjrbtfcgvkmany,qywzphxoiselzcrbtfcgvkmanz,qywzphxoisxodjrbtscgvkmanu,qywzphxoiseldjrrtfcgmkmaeu,aywzphxoiseldjrbtfmjvkmanu,qywzthxoiiewdjrbtfcgvkmanu,qywzpsxoisrzdjrbtfcgvkmanu,qywzphxoiseldjkbtqcgvkmank,tywzphxoisewdjkbtfcgvkmanu,qywkchxoiseldjrbtfcghkmanu,qywzphxoiseldjoftfrgvkmanu,qywzpixoisehdjrbtfcgvkmacu,qywzchooiseldarbtfcgvkmanu,qywyphtoaseldjrbtfcgvkmanu,qywyphxotsbldjrbtfcgvkmanu,qywzphxoiseldjrbhsggvkmanu,dywzphxoiseldjrktfegvkmanu,qywzphxoiseldjrmtfcgvkcenu,qywcphxjiseldjybtfcgvkmanu,qywzphxoiseldhrbsfogvkmanu,qmwzpheoiseldjrrtfcgvkmanu,qywzrhxoiselpjrbtfcgvemanu,qyezphpoiseldjrbtfcgvdmanu,qywzphxvisewdjrbtfcgvkmdnu,qywzphkoiseldjrbtfcgvkmdnh,qywzehxoiseldfrbtpcgvkmanu,qywzphxoiseldjrrtfcgvrdanu,qpwzphxoizeldjqbtfcgvkmanu,qywzphxojseldjrbtmcgvkmvnu,vywzphxoiseldjrbtfcgvkmaop,sywzphxoiselbjrttfcgvkmanu,qywwphkoiseldjrbtfcivkmanu,qlwkpcxoiseldjrbtfcgvkmanu,qywzphxoiyesdjrbtfcgvkmvnu,qywzphxoiseldjrbofcgrkmrnu,qywzphxyiseldjrstfcgvkmjnu,qywzphaoiseldtrbnfcgvkmanu,qywzphxhisuldurbtfcgvkmanu,qywzphxdiseldjrbtvugvkmanu,qywzpzxbiseldjrbtfcgukmanu,qyrzphxoixeldjrbtfcgvumanu,qywzphxoiberdjrptfcgvkmanu,qywzphxfiskldjrbtfcgvkmdnu,qyxzphxoiseldjrdhfcgvkmanu,qywzphrqiseldjrbtfcgvbmanu,qyezphxviseldjrbtfcgvkmani,qywgphxoiseldgkbtfcgvkmanu,qywzphxoileldjrbtgcgvkdanu,qywzphxoiseldnrbtfcwvkmpnu,qywzphxoiseidjrbmfcqvkmanu,qywzpkxoiselijrbtfcgvlmanu,mywzphxoiveldjrbtfcgvkmunu,qywzphxooseddjrbtfcgpkmanu,qywzphxokseldjritfcyvkmanu,qywzxhxoiseldjrbtfqgvcmanu,qywzphxoisfldjrbpfcgvkmaju,qywuphxgiseldjrbffcgvkmanu,qywzphociseldjrbtfcgvkuanu,qywzphxoiseldvrbtftgckmanu,qywzpbxoisrldjrbtfngvkmanu,qywzphxoiseldjrntfygvdmanu,qywzphxviseldkrbtfcgvkianu,qywpphxgiseldjrbtfctvkmanu,qywzphxoicewdjrbtfcgvsmanu,qywzpcxoiseldjmbtfcgvcmanu,qrwzphxoiseldjrbtfcgjumanu,qywzphxoiselojrbtfcgxkmaau,qywzphxojsbldjrbtfcgykmanu,oywzphxoiseldjrbtfqgvkmvnu,qywfphxpiseldjrbtfckvkmanu,qyyzwhxwiseldjrbtfcgvkmanu,qywzphxgiseldjrbtfchvkmabu,qywzphxfiseldjrbtfcgukoanu,qywzpdxoisyldjrbtfcgvkxanu,dyuzphxoiseldjrbtfcgvkmamu,qywzphxoiseldjrbifcgvkmnnp,qywzpyxoiseldjrbtfcgvklano,dywzphxoiieldjrbtfcgvwmanu,qywzphxoihemdjrbtfcgvdmanu,gywzphxoxseldvrbtfcgvkmanu,qywzqhxoissldjwbtfcgvkmanu,eywzphxoiieldjrbtfcgekmanu,qyizprxciseldjrbtfcgvkmanu,qywjphxoiseldjrbtfcgckmano,qywznhxoiseldjrbrfcgvkmagu,qywzphxoisrldjdbvfcgvkmanu,qyyxphxoiseldjrbtwcgvkmanu,qywzphxoiseldjdbtfcpvkmjnu,qywzvhxqiseldjrbofcgvkmanu,vywzphxoiseldjrbtfcgckwanu,qywzphgbiseldjrbtfcgvkmazu,qcwzphxoiseldjrbqfcgvkmdnu,qywzphxoismldjrbtfcgkkmznu,qywhphxoiseldjrbtccgvkmane,qywzphzoiseldjrbtfcgvqmauu,hywzphxoiseldjrbtfcuvkmanc,qywzphxozsejdgrbtfcgvkmanu,qyszphxoiseldjrntfygvdmanu,qywzphxoisgldjrbtfcgvklaru,qywzhhxoiseldjrbtscgvkmqnu,qywjphxpiqeldjrbtfcgvkmanu,qywzphxoiseldxrptfclvkmanu,qywlphxoisehdjrbtfcgvkmanc,qydzpfxoiseldjrwtfcgvkmanu,qywzphxoiseldjrbtxcgqkfanu,qywophxoiselfjrbtfcgvkmani,qywzyhxoiszldtrbtfcgvkmanu,qywzphxoxseldfrntfcgvkmanu,qywzphloiseldjqbtfcgvkmtnu,qywzpuxoiseldorbtfcgvkeanu,qywzphxoiueldjrwdfcgvkmanu,qgwzphxoiseldjmbtncgvkmanu,qywzphtggseldjrbtfcgvkmanu,qywzphxoisrldjrbtfmgvhmanu,qfszphxoiseldjqbtfcgvkmanu,qywzphxpisjldjrbxfcgvkmanu,qywznhxoisepdjrbtfqgvkmanu,qywzphioiseldjabtfcgxkmanu,qyizphxaiseldjrbtfcgvkmaxu,xywzphxoiqelvjrbtfcgvkmanu,quwzphxoiseldjretfcgvkmaau,bywzphxoiseldjrbtucgckmanu,jywzphxoiseldjrbofcgvkmani,qywzphxoiseltjkbtfcgvkmabu,eywzphxoiselgjrbtfkgvkmanu,qywzphxoisengjrttfcgvkmanu,qywzphzoiseldjrbtfcgvkmknk,quwdphxoiseldjrbtfcxvkmanu,qcwzzhxoiseldjrgtfcgvkmanu,qywgphxdiseldjrbtfcgjkmanu,qywzpdxoivefdjrbtfcgvkmanu,qywzphxoiseldjrbtfdgvjmpnu,qfwzphxoiseydkrbtfcgvkmanu,qywzphxdiqelqjrbtfcgvkmanu,qywzvhxoiseldjrbtfognkmanu,qywzphgoiseldjrbcfcgvtmanu,qywophxoiseldjrbtpcgvkmank,qywzphxoiszldjretfcgvkmabu,qywzphxoiseldjhbtfcgvxmawu,qcgzphxoiselejrbtfcgvkmanu,qywzphxoisepdjrbtfcfvkcanu,qivzphxniseldjrbtfcgvkmanu,qywzhhxoiseldjrftxcgvkmanu,qyazphxciseldjrbtfcgskmanu,qywzphxoisoldgrbtfczvkmanu,qywzmhxoiseldurbwfcgvkmanu,qywzphxoistldjrbwfcgvkranu,qywzphxoistedjrbtfcgokmanu,qywzqhxodsecdjrbtfcgvkmanu,qywzphxtisxldjrbtfcgvkhanu,qywzphxoeseldjrtrfcgvkmanu,qdwzphxoioeldjrbtfigvkmanu,qjwzphxoisbldjrbtfcgvkmanz,qywzphxoiseldbrbtfdgvlmanu,qywzphxoiselddrbhvcgvkmanu,zywzppxoiseldjrdtfcgvkmanu,qywzppxqiselkjrbtfcgvkmanu,qywzphxoihelbjrbtfcgvkmabu,qywzphxoiseldjreyfcgvknanu,qywzphxxrseldjrbtfcgvkmagu,qywhpfxoiseldjrbtfdgvkmanu,qywzphxoisxldjrdtfagvkmanu,oywzphxxiseldjrbtfcgvkmaeu,qywzphxoiselqirbtfvgvkmanu,qywzphxoqseldhrbtfcgvkhanu,qywzphxokseldjrbtfxgvkmaju,qywzphtoiseldurbtfcfvkmanu,qywzphxoiheudjrrtfcgvkmanu,qrwzphxzigeldjrbtfcgvkmanu,qywzphxoiseldorbtfcgvxmvnu,qywzphxoisaldjpbqfcgvkmanu,qywuphxoiselljrbtfchvkmanu,qywzphxoisaldjrbefcgvkmsnu,qywzphxoiteldjrbnfcgvkmanp,qywhphxoiselqjrbtfcgvkmagu,qywzjhxoisejdjrbtfcgvkmanr,qywephaoiseldjrbtfcavkmanu,qywcphxoireldjqbtfcgvkmanu,qywzphxoiseldirbuicgvkmanu,qywzphxoisecvnrbtfcgvkmanu,qcwzphxoiseldjrbtfcgvrmaiu,qywnphxoiseldjrntftgvkmanu,qywzphxhisyldjrbtfcgvkmafu,qyhzphxoiseldjrytfcgvkmanq,vjwzbhxoiseldjrbtfcgvkmanu,qyvzpsxoisuldjrbtfcgvkmanu,qywzphxaiseldcrbefcgvkmanu,qywzphxoiseldjgbtfsgvkfanu,oiwzphxoiseldjrbtfcgvkmcnu,qyezphxoiseldjrbtfcqvkmjnu,tywzphxriseldzrbtfcgvkmanu,yywzphxoiseldjbbtfugvkmanu,qywzpfxviseldjrbttcgvkmanu,qywzphxoiceldcrbtfugvkmanu,qymzphxoiseldjratfcsvkmanu,qywzphxoiselxjrbdfcgvkpanu,qywzphxoiselujrbtfkgvimanu,qywzshyoiseldjrbtfcgpkmanu,qywzphxoiselfjrbtfsgvkmant,qywpphxoiseldjxbtfcyvkmanu,qywzfhxoiselqjrptfcgvkmanu,qewzphxoiseldprbtfcgvkmand,qywfphxoiseldlrbtfcgvkmgnu,qywzphxoiseldjhbtqcovkmanu,fywzphxoiseldlrbtfcgvkjanu,sywzphxoiseldjrbhfccvkmanu,qywzphxoiseldjfbtfcrvkmpnu,sywzphxoisrldjrbtfczvkmanu'

matches = {
	2: 0,
	3: 0
}
similar_inputs = []

inputs = input.split(',')

# Part 1 = 5478
for input in inputs:
	length = len(input)
	current_count = {}
	for i in range (0, length):
		if (input[i] in current_count):
			current_count[input[i]] += 1
		else:
			current_count[input[i]] = 1

	found_3 = False
	found_2 = False

	for letter, count in current_count.items():
		if count is 3 and found_3 is False:
			found_3 = True
			matches[3] += 1
			similar_inputs.append(input)
		elif count is 2 and found_2 is False:
			found_2 = True
			matches[2] += 1
			similar_inputs.append(input)

print('Part 1: ' + str(matches[2] * matches[3]))

# Part 2 = qyzphxoiseldjrntfygvdmanu
best_answer = ''
for i, input in enumerate(similar_inputs):
	length = len(input)
	for ii, sub_input in enumerate(similar_inputs):
		if i is ii:
			continue

		matching = ''
		for iii in range (0, length):
			if input[iii] is sub_input[iii]:
				matching += input[iii]

		if matching and len(matching) is length - 1:
			best_answer = matching

print('Part 2: ' + best_answer)